# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_priority',
        ),
    ]
