# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
