# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_id',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
