# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20170427_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
