# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
